@c Copyright (C) 1991-2015 Free Software Foundation, Inc.
@c This is part of the GAS manual.
@c For copying conditions, see the file as.texinfo.
@page
@node AAP-dependent
@section AAP Dependent Features

@cindex AAP
AAP is a free and open source 16/32-bit word-addressed Harvard
architecture, developed to support experimentation with compiler
features for such architectures.  AAP is documented in
@url{http://www.embecosm.com/download/ean13.html, Embecosm Application
Note 13. AAP: An Altruistic Processor}.

The LLVM integrated assembler for AAP has relatively few custom features.

@menu
* AAP Options::   	AAP Specific Command Line Options
* AAP Directives::      AAP Specific Assembler Directives
* AAP Assembler Syntax::  AAP Assembler Syntax
@end menu

@node AAP Options
@subsection AAP Specific Commmand Line Options
@cindex command line options for AAP
@cindex AAP, command line options
AAP configurations of the LLVM integrated assembler support these
special options:

@table @code
@item -Q @var{num}
@cindex @code{-Q} option (AAP)
An example option to complete the template.
@end table

@node AAP Directives
@subsection AAP Specific Assembler Directives
@cindex assembler directives for AAP
@cindex AAP, assembler directives

AAP configurations of the LLVM integrated assembler support these
special assembler directives and variants of standard directives.

@table @code
@item .AAP
@cindex @code{AAP} directive (AAP)
@cindex @code{.AAP} (AAP)

@end table

@node AAP Assembler Syntax
@subsection AAP Assembler Syntax

The following are custom assembler syntax.

@table @strong
@item line comment character
@cindex line comment character, AAP
@cindex AAP line comment character
The presence of a @samp{#} on a line indicates the start of a comment
that extends to the end of the current line.

If a @samp{#} appears as the first character of a line, the whole line
is treated as a comment, but in this case the line can also be a
logical line number directive (@pxref{Comments}) or a
preprocessor control command (@pxref{Preprocessing}).

@item line separator
@cindex line separator, AAP
@cindex statement separator, AAP
@cindex AAP line separator
There is no line separator character for AAP.  Each assembler
statement must be on its own line.

@end table
